/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlinhansu;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Administrator
 */
public class frm_QUANLYNHANVIEN extends javax.swing.JFrame {
DanhSachNV danhSach;
    /**
     * Creates new form frm_QUANLYNHANVIEN
     */
    public frm_QUANLYNHANVIEN() {
        initComponents();
        this.danhSach=new DanhSachNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Manv = new javax.swing.JTextField();
        txt_Hoten = new javax.swing.JTextField();
        txt_Ngayvaocoquan = new javax.swing.JTextField();
        rdo_Nhanvienbienche = new javax.swing.JRadioButton();
        rdo_Nhanvienhopdong = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_Hesoluong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Mucluong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Thamnien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Phucap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Thuclinh = new javax.swing.JTextField();
        btn_Themmoi = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Tim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Họ tên");

        jLabel4.setText("Ngày vào cơ quan");

        txt_Ngayvaocoquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayvaocoquanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_Nhanvienbienche);
        rdo_Nhanvienbienche.setText("Nhân viên biên chế");

        buttonGroup1.add(rdo_Nhanvienhopdong);
        rdo_Nhanvienhopdong.setText("Nhân viên hợp đồng");

        jLabel5.setText("Hệ số lương");

        jLabel6.setText("Mức lương");

        jLabel7.setText("Thâm niên");

        jLabel8.setText("Phụ cấp");

        jLabel9.setText("Thực lĩnh");

        btn_Themmoi.setText("Thêm mới");
        btn_Themmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemmoiActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Tim.setText("Tìm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Ngayvaocoquan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Manv)
                                    .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_Nhanvienbienche)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Hesoluong)
                                    .addComponent(txt_Thamnien)
                                    .addComponent(txt_Thuclinh, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_Nhanvienhopdong)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Mucluong)
                                    .addComponent(txt_Phucap, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btn_Themmoi)
                        .addGap(33, 33, 33)
                        .addComponent(btn_Xoa)
                        .addGap(43, 43, 43)
                        .addComponent(btn_Sua)
                        .addGap(41, 41, 41)
                        .addComponent(btn_Tim)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_Nhanvienbienche)
                    .addComponent(rdo_Nhanvienhopdong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Hesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Mucluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Ngayvaocoquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Phucap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Thuclinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Themmoi)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Tim))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemmoiActionPerformed
         nhanvien nv;
         String Manv=txt_Manv.getText();
         String hoten=txt_Hoten.getText();
         String ngayvaocoquan=txt_Ngayvaocoquan.getText();
         SimpleDateFormat d=new SimpleDateFormat();
         Date ngayvao=null;
         try{
         ngayvao=d.parse(ngayvaocoquan);
         }catch (Exception ex ){}
         if(rdo_Nhanvienbienche.isSelected())
         {
             double hesoluong= Double.parseDouble(txt_Hesoluong.getText());
            nv=new NhanVienBC(hesoluong,Manv,hoten,ngayvao);
         }
         else 
         {
            double mucluong=Double.parseDouble(txt_Mucluong.getText());
            nv=new NhanVienHopDong(mucluong,Manv,hoten,ngayvao);
         }
         this.danhSach.nhap(nv);
         
        
    }//GEN-LAST:event_btn_ThemmoiActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        String Manv=txt_Manv.getText();
        this.danhSach.xoa(Manv);
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
         nhanvien nv;
         String Manv=txt_Manv.getText();
         String hoten=txt_Hoten.getText();
         String ngayvaocoquan=txt_Ngayvaocoquan.getText();
         SimpleDateFormat d=new SimpleDateFormat();
         Date ngayvao=null;
         try{
         ngayvao=d.parse(ngayvaocoquan);
         }catch (Exception ex ){}
         if(rdo_Nhanvienbienche.isSelected())
         {
             double hesoluong= Double.parseDouble(txt_Hesoluong.getText());
            nv=new NhanVienBC(hesoluong,Manv,hoten,ngayvao);
         }
         else 
         {
            double mucluong=Double.parseDouble(txt_Mucluong.getText());
            nv=new NhanVienHopDong(mucluong,Manv,hoten,ngayvao);
         }
         this.danhSach.sua(nv);
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_NgayvaocoquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayvaocoquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayvaocoquanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QUANLYNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QUANLYNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QUANLYNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QUANLYNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QUANLYNHANVIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Themmoi;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdo_Nhanvienbienche;
    private javax.swing.JRadioButton rdo_Nhanvienhopdong;
    private javax.swing.JTextField txt_Hesoluong;
    private javax.swing.JTextField txt_Hoten;
    private javax.swing.JTextField txt_Manv;
    private javax.swing.JTextField txt_Mucluong;
    private javax.swing.JTextField txt_Ngayvaocoquan;
    private javax.swing.JTextField txt_Phucap;
    private javax.swing.JTextField txt_Thamnien;
    private javax.swing.JTextField txt_Thuclinh;
    // End of variables declaration//GEN-END:variables
}
